# Generated by Django 4.1.2 on 2022-10-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_streamingplatform_rename_name_movie_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamingPlatform',
            new_name='StreamPlatform',
        ),
    ]
