# Generated by Django 4.1.2 on 2022-10-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_rename_streamingplatform_streamplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='watchlist.streamplatform'),
            preserve_default=False,
        ),
    ]
